app:
  queries: {}
#    select1:
#      verb: post
#      queryBuilderClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.query.DefaultQueryBuilder'
#      resultSetConvertorClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.rs.DefaultResultSetConvertor'
#      jsonConvertorClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.json.NoOpConvertor'
#      query: |-
#        SELECT 1                as simple,
#               ['a', 'b', 'c']  as simpleArray,
#               {a: 65}          as simpleStruct,
#               {a: 65, b: [58]} as simpleStruct,
#    select2:
#      doc:
#        summary: Example
#        description: Long description
#      verb: post
#      returnedStruct:
#        simple: int
#        simpleArray: list<string>
#      queryBuilderClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.query.DefaultQueryBuilder'
#      resultSetConvertorClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.rs.DefaultResultSetConvertor'
#      jsonConvertorClass: 'fr.qgo.duckdbrestapi.service.defaultimpl.json.NoOpConvertor'
#      payloadStruct:
#        field1:
#          type: string
#          defaultValue: hello world
#        field2:
#          type: Integer
#        field3:
#          type: int
#        field4:
#          type: list<Integer>
#          defaultValue: '[]'
#        field5:
#          type: set<Integer>
#        field6:
#          type: map<String, Integer>
#      query: |-
#        SELECT 1                as simple,
#               ['a', 'b', 'c']  as simpleArray,
#               {a: 65}          as simpleStruct,
#               {a: 65, b: [58]} as complexStruct,

logging:
  level:
    fr.qgo.duckdbrestapi.duckdb.C3P0InitConnection: DEBUG